=== A3928543/dev/SICA_MIG_SERV_ESB_MCA/commons/banorte/resources/consultaInformacionCuenta/ConsultaInfoResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.banorte.com/ws/esb/ConsultaInfoResponse" xmlns:tns="http://www.banorte.com/ws/esb/ConsultaInfoResponse" elementFormDefault="qualified">
	<xsd:complexType name="BGM1621">
		<xsd:sequence>
			<xsd:element name="FechaProceso" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:int">
						<xsd:pattern value="([0-9]{1,8})"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NumeroCuenta" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="10"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="ClabeCuenta" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="21"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="CR" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="DescripcionSucursal" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="40"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoInicial" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
        				<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
        			</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="TipoDivisa" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoDisponible" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoRetenido" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoDia" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="RegimenFirmas" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="15"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NombrePromotor" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="60"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BGM1622">
		<xsd:sequence>
			<xsd:element name="FechaProceso" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:int">
						<xsd:pattern value="([0-9]{1,8})"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NumeroCuenta" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="10"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="CuentaAsociada" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="10"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NumeroCliente" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="8"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NombreCliente" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="62"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="RFC" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="13"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NombreCalle" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="30"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Numero" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="7"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NombreColonia" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="30"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="EntidadFederativa" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="20"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NombreCiudad" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="20"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="CodigoPostal" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="7"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Telefono" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="15"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="TipoProducto" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="2"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SubProducto" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="DescSubProducto" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="30"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="StatusCuenta" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="15"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="CR" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="DescSucursal" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="40"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="FechaApertura" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:int">
						<xsd:pattern value="([0-9]{1,8})"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="FechaVencimiento" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:int">
						<xsd:pattern value="([0-9]{1,8})"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="TipoDivisa" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="CuentaClabe" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="21"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoPromedio" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="CodigoRetencion" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Regimen" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="20"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SusceptibilidadPlast">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Titularidad" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="3"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="Claveregimen" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="CodigoBloqueo" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="50"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SituacionCuenta" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="50"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="BloqueoJudicial" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="50"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="BloqueoAdmon" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="50"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="LiquidacionInte" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="LineaPrivilegios" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="MontoServicio" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="EstatusLinPriv" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:int">
						<xsd:maxInclusive value="9999"></xsd:maxInclusive>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="IndServicio" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="IndComision" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="1"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="RegimenFirmas" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="15"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NombrePromotor" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="60"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence> 
	</xsd:complexType>
	<xsd:complexType name="BGM1623">
		<xsd:sequence>
			<xsd:element name="FechaProceso" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:int">
						<xsd:pattern value="([0-9]{1,8})"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="NumeroCuenta" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="10"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="ClabeCuenta" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="21"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="CR" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="DescripcionSucursal" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="40"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoInicial" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
        				<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
        			</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="TipoDivisa" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="4"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoDisponible" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoRetenido" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoDia" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:decimal">
						<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="SaldoMesAnterior" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="(([0-9]{1,16})([.])([0-9]{1,2}))"></xsd:pattern>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="RegimenFirmas" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="15"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BGM1624">
		<xsd:sequence>
			<xsd:element name="DescripcionBloqueo" minOccurs="1" maxOccurs="1">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:maxLength value="34"></xsd:maxLength>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BGM1625">
		<xsd:sequence>
			<xsd:element name="Titulo1" minOccurs="1" maxOccurs="1" type="xsd:string"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="BGM1626">
		<xsd:sequence>
			<xsd:element name="FecFinM" minOccurs="1" maxOccurs="1" type="xsd:string"></xsd:element>
			<xsd:element name="Saldo" minOccurs="1" maxOccurs="1" type="xsd:string"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ConsultaInfoCuentaResponse">
		<xsd:sequence>
			<xsd:element name="Bgm1621" minOccurs="0" maxOccurs="1" type="tns:BGM1621"></xsd:element>
			<xsd:element name="Bgm1622" minOccurs="0" maxOccurs="1" type="tns:BGM1622"></xsd:element>
			<xsd:element name="Bgm1623" minOccurs="0" maxOccurs="1" type="tns:BGM1623"></xsd:element>
			<xsd:element name="Bgm1624" minOccurs="0" maxOccurs="unbounded" type="tns:BGM1624"></xsd:element>
			<xsd:element name="Bgm1625" minOccurs="0" maxOccurs="1" type="tns:BGM1625"></xsd:element>
			<xsd:element name="Bgm1626" minOccurs="0" maxOccurs="unbounded" type="tns:BGM1626"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="ConsultaInfoCuentaResponse" type="tns:ConsultaInfoCuentaResponse"></xsd:element>
</xsd:schema>

=== A3928543/dev/SICA_MIG_SERV_ESB_MCA/commons/banorte/resources/consultaInformacionCuenta/ConsultaInfoResponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:ConsultaInfoCuentaResponse xmlns:tns="http://www.banorte.com/ws/esb/ConsultaInfoResponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.banorte.com/ws/esb/ConsultaInfoResponse ConsultaInfoResponse.xsd ">
  <tns:Bgm1621>
    <tns:FechaProceso>0</tns:FechaProceso>
    <tns:NumeroCuenta>tns:NumeroCuenta</tns:NumeroCuenta>
    <tns:ClabeCuenta>tns:ClabeCuenta</tns:ClabeCuenta>
    <tns:CR>tns:CR</tns:CR>
    <tns:DescripcionSucursal>tns:DescripcionSucursal</tns:DescripcionSucursal>
    <tns:SaldoInicial>0.0</tns:SaldoInicial>
    <tns:TipoDivisa>tns:TipoDivisa</tns:TipoDivisa>
    <tns:SaldoDisponible>0.0</tns:SaldoDisponible>
    <tns:SaldoRetenido>0.0</tns:SaldoRetenido>
    <tns:SaldoDia>0.0</tns:SaldoDia>
    <tns:RegimenFirmas>tns:RegimenFirmas</tns:RegimenFirmas>
    <tns:NombrePromotor>tns:NombrePromotor</tns:NombrePromotor>
  </tns:Bgm1621>
  <tns:Bgm1622>
    <tns:FechaProceso>0</tns:FechaProceso>
    <tns:NumeroCuenta>tns:NumeroCuenta</tns:NumeroCuenta>
    <tns:CuentaAsociada>tns:CuentaAsociada</tns:CuentaAsociada>
    <tns:NumeroCliente>tns:NumeroCliente</tns:NumeroCliente>
    <tns:NombreCliente>tns:NombreCliente</tns:NombreCliente>
    <tns:RFC>tns:RFC</tns:RFC>
    <tns:NombreCalle>tns:NombreCalle</tns:NombreCalle>
    <tns:Numero>tns:Numero</tns:Numero>
    <tns:NombreColonia>tns:NombreColonia</tns:NombreColonia>
    <tns:EntidadFederativa>tns:EntidadFederativa</tns:EntidadFederativa>
    <tns:NombreCiudad>tns:NombreCiudad</tns:NombreCiudad>
    <tns:CodigoPostal>tns:CodigoPostal</tns:CodigoPostal>
    <tns:Telefono>tns:Telefono</tns:Telefono>
    <tns:TipoProducto>tns:TipoProducto</tns:TipoProducto>
    <tns:SubProducto>tns:SubProducto</tns:SubProducto>
    <tns:DescSubProducto>tns:DescSubProducto</tns:DescSubProducto>
    <tns:StatusCuenta>tns:StatusCuenta</tns:StatusCuenta>
    <tns:CR>tns:CR</tns:CR>
    <tns:DescSucursal>tns:DescSucursal</tns:DescSucursal>
    <tns:FechaApertura>0</tns:FechaApertura>
    <tns:FechaVencimiento>0</tns:FechaVencimiento>
    <tns:TipoDivisa>tns:TipoDivisa</tns:TipoDivisa>
    <tns:CuentaClabe>tns:CuentaClabe</tns:CuentaClabe>
    <tns:SaldoPromedio>0.0</tns:SaldoPromedio>
    <tns:CodigoRetencion>tns:CodigoRetencion</tns:CodigoRetencion>
    <tns:Regimen>tns:Regimen</tns:Regimen>
    <tns:SusceptibilidadPlast>tns:SusceptibilidadPlast</tns:SusceptibilidadPlast>
    <tns:Titularidad>tns:Titularidad</tns:Titularidad>
    <tns:Claveregimen>tns:Claveregimen</tns:Claveregimen>
    <tns:CodigoBloqueo>tns:CodigoBloqueo</tns:CodigoBloqueo>
    <tns:SituacionCuenta>tns:SituacionCuenta</tns:SituacionCuenta>
    <tns:BloqueoJudicial>tns:BloqueoJudicial</tns:BloqueoJudicial>
    <tns:BloqueoAdmon>tns:BloqueoAdmon</tns:BloqueoAdmon>
    <tns:LiquidacionInte>tns:LiquidacionInte</tns:LiquidacionInte>
    <tns:LineaPrivilegios>tns:LineaPrivilegios</tns:LineaPrivilegios>
    <tns:MontoServicio>0.0</tns:MontoServicio>
    <tns:EstatusLinPriv>0</tns:EstatusLinPriv>
    <tns:IndServicio>tns:IndServicio</tns:IndServicio>
    <tns:IndComision>tns:IndComision</tns:IndComision>
    <tns:RegimenFirmas>tns:RegimenFirmas</tns:RegimenFirmas>
    <tns:NombrePromotor>tns:NombrePromotor</tns:NombrePromotor>
  </tns:Bgm1622>
  <tns:Bgm1623>
    <tns:FechaProceso>0</tns:FechaProceso>
    <tns:NumeroCuenta>tns:NumeroCuenta</tns:NumeroCuenta>
    <tns:ClabeCuenta>tns:ClabeCuenta</tns:ClabeCuenta>
    <tns:CR>tns:CR</tns:CR>
    <tns:DescripcionSucursal>tns:DescripcionSucursal</tns:DescripcionSucursal>
    <tns:SaldoInicial>0.0</tns:SaldoInicial>
    <tns:TipoDivisa>tns:TipoDivisa</tns:TipoDivisa>
    <tns:SaldoDisponible>0.0</tns:SaldoDisponible>
    <tns:SaldoRetenido>0.0</tns:SaldoRetenido>
    <tns:SaldoDia>0.0</tns:SaldoDia>
    <tns:SaldoMesAnterior>tns:SaldoMesAnterior</tns:SaldoMesAnterior>
    <tns:RegimenFirmas>tns:RegimenFirmas</tns:RegimenFirmas>
  </tns:Bgm1623>
  <tns:Bgm1624>
    <tns:DescripcionBloqueo>tns:DescripcionBloqueo</tns:DescripcionBloqueo>
  </tns:Bgm1624>
  <tns:Bgm1625>
    <tns:Titulo1>tns:Titulo1</tns:Titulo1>
  </tns:Bgm1625>
  <tns:Bgm1626>
    <tns:FecFinM>tns:FecFinM</tns:FecFinM>
    <tns:Saldo>tns:Saldo</tns:Saldo>
  </tns:Bgm1626>
</tns:ConsultaInfoCuentaResponse>
